### PR TITLE
Style a 404 page

### PR DESCRIPTION
**Pull request by lizzypine**
_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

- Created a cheeky 404 page.
- Updated React Router so that when user goes to a nonexistent page they are routed to the 404 page.
- Bonus scope creep: Updated React Router so if user does not have a list token and they try to go to the add item page, they are navigated to the homepage (before, if a user didn't have a token they could go to the add item page, but then they would get an error if they tried to add an item to their nonexistent list).

Closes issue #33 

## Acceptance Criteria

- User is brought to the 404 page if they try navigating to a nonexistent page.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
| ✓    | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before

Screenshot 2023-05-25 at 8 28 20 AM

### After

Screenshot 2023-05-25 at 8 29 00 AM

## Testing Steps / QA Criteria

To test the 404 page:
- Open up your browser
- Try navigating to a nonexistent page (e.g., http://localhost:3000/somepage)

To test the updated routing:
- Remove your list token and refresh the app.
- Try going straight to the add item view. You will be rerouted to the homepage since you don't have a list token.

### CODE REVIEW

**Review by itsoliviasparks — APPROVED** [review]
This is so stinkin' cute!!

**Review by itsoliviasparks — APPROVED** [review]
This is so stinkin' cute!!

**Review by 01001101CK — APPROVED** [review]
Predict a lost! So cute...

**Review by hansontram — APPROVED** [review]
Great job on fixing the addItem bug. Predict-a-lost is hilarious! 😂

**Comment by lizzypine** [comment]
Super! Thanks, everyone. I will go ahead and merge this 404 page stuff into the main `styling` branch.

**Pull request merged**
